---
# tasks file for weaveinstall
- name: Download and Install Weave
  get_url: url={{ weave_url }} dest={{weave_bin }}

- name: Setup Weave Permissions 
  file: path={{ weave_bin }} mode="u+rx,g+rx,o+rwx"

- name: Download Weave Containers
  command: weave setup

- name: Launch Weave 
  command: weave launch
